version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/docker/${repository}/log:/var/docker/${repository}/log"
    networks:
      - ${repository}net
      - influxdbnet

networks:
  ${repository}net:
    name: ${repository}net
  influxdbnet:
    external: true
    name: influxdbnet
